/** 面板尺寸 */
export const LEFT_LAYOUT_SIZE = 'LEFT_LAYOUT_SIZE'
export const RIGHT_LAYOUT_SIZE = 'RIGHT_LAYOUT_SIZE'
export const VIEW_LAYOUT_SIZE = 'VIEW_LAYOUT_SIZE'
export const WORK_VIEW_LAYOUT_SIZE = 'WORK_VIEW_LAYOUT_SIZE'

/** 信号 */
export const EMIT_PAGE_LOADED = 'EMIT_PAGE_LOADED'
